### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by lightda104530** [Rex-Tech/MyNPC#1]
The number of skin is so long~can it be fix?

**Comment by RexRed6802** [comment]
Maybe~~ i'll fix it tomorrow~

**Comment by lightda104530** [comment]
Got it!

**Comment by RexRed6802** [comment]
done!

**Comment by lightda104530** [comment]
Can use on 0.16??

**Comment by RexRed6802** [comment]
It wasn't tested in 0.16 server

**Comment by lightda104530** [comment]
0.16 serrver this plugin wil run error when you spawn a npc

**Comment by RexRed6802** [comment]
I'll test it tomorrow
